In [160]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import plotly.express as px
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

In [161]:
df = pd.read_csv('data/features_3_sec.csv')
df['label'] = df['label'].astype('category')
df.head()

filename  length  chroma_stft_mean  chroma_stft_var  rms_mean  \
0  blues.00000.0.wav   66149          0.335406         0.091048  0.130405   
1  blues.00000.1.wav   66149          0.343065         0.086147  0.112699   
2  blues.00000.2.wav   66149          0.346815         0.092243  0.132003   
3  blues.00000.3.wav   66149          0.363639         0.086856  0.132565   
4  blues.00000.4.wav   66149          0.335579         0.088129  0.143289   

    rms_var  spectral_centroid_mean  spectral_centroid_var  \
0  0.003521             1773.065032          167541.630869   
1  0.001450             1816.693777           90525.690866   
2  0.004620             1788.539719          111407.437613   
3  0.002448             1655.289045          111952.284517   
4  0.001701             1630.656199           79667.267654   

   spectral_bandwidth_mean  spectral_bandwidth_var  ...  mfcc16_var  \
0              1972.744388           117335.771563  ...   39.687145   
1              2010.051501            65671.875673  ...   64.748276   
2              2084.565132            75124.921716  ...   67.336563   
3              1960.039988            82913.639269  ...   47.739452   
4              1948.503884            60204.020268  ...   30.336359   

   mfcc17_mean  mfcc17_var  mfcc18_mean  mfcc18_var  mfcc19_mean  mfcc19_var  \
0    -3.241280   36.488243     0.722209   38.099152    -5.050335   33.618073   
1    -6.055294   40.677654     0.159015   51.264091    -2.837699   97.030830   
2    -1.768610   28.348579     2.378768   45.717648    -1.938424   53.050835   
3    -3.841155   28.337118     1.218588   34.770935    -3.580352   50.836224   
4     0.664582   45.880913     1.689446   51.363583    -3.392489   26.738789   

   mfcc20_mean  mfcc20_var  label  
0    -0.243027   43.771767  blues  
1     5.784063   59.943081  blues  
2     2.517375   33.105122  blues  
3     3.630866   32.023678  blues  
4     0.536961   29.146694  blues  

[5 rows x 60 columns]

In [162]:
df.count()

filename                   9990
length                     9990
chroma_stft_mean           9990
chroma_stft_var            9990
rms_mean                   9990
rms_var                    9990
spectral_centroid_mean     9990
spectral_centroid_var      9990
spectral_bandwidth_mean    9990
spectral_bandwidth_var     9990
rolloff_mean               9990
rolloff_var                9990
zero_crossing_rate_mean    9990
zero_crossing_rate_var     9990
harmony_mean               9990
harmony_var                9990
perceptr_mean              9990
perceptr_var               9990
tempo                      9990
mfcc1_mean                 9990
mfcc1_var                  9990
mfcc2_mean                 9990
mfcc2_var                  9990
mfcc3_mean                 9990
mfcc3_var                  9990
mfcc4_mean                 9990
mfcc4_var                  9990
mfcc5_mean                 9990
mfcc5_var                  9990
mfcc6_mean                 9990
mfcc6_var                  9990
mfcc7_me

In [163]:
df.dtypes

filename                     object
length                        int64
chroma_stft_mean            float64
chroma_stft_var             float64
rms_mean                    float64
rms_var                     float64
spectral_centroid_mean      float64
spectral_centroid_var       float64
spectral_bandwidth_mean     float64
spectral_bandwidth_var      float64
rolloff_mean                float64
rolloff_var                 float64
zero_crossing_rate_mean     float64
zero_crossing_rate_var      float64
harmony_mean                float64
harmony_var                 float64
perceptr_mean               float64
perceptr_var                float64
tempo                       float64
mfcc1_mean                  float64
mfcc1_var                   float64
mfcc2_mean                  float64
mfcc2_var                   float64
mfcc3_mean                  float64
mfcc3_var                   float64
mfcc4_mean                  float64
mfcc4_var                   float64
mfcc5_mean                  

In [164]:
df['label'].unique()

['blues', 'classical', 'country', 'disco', 'hiphop', 'jazz', 'metal', 'pop', 'reggae', 'rock']
Categories (10, object): ['blues', 'classical', 'country', 'disco', ..., 'metal', 'pop', 'reggae', 'rock']

###### Buscar datos nulos

In [165]:
df.isnull().sum()

filename                   0
length                     0
chroma_stft_mean           0
chroma_stft_var            0
rms_mean                   0
rms_var                    0
spectral_centroid_mean     0
spectral_centroid_var      0
spectral_bandwidth_mean    0
spectral_bandwidth_var     0
rolloff_mean               0
rolloff_var                0
zero_crossing_rate_mean    0
zero_crossing_rate_var     0
harmony_mean               0
harmony_var                0
perceptr_mean              0
perceptr_var               0
tempo                      0
mfcc1_mean                 0
mfcc1_var                  0
mfcc2_mean                 0
mfcc2_var                  0
mfcc3_mean                 0
mfcc3_var                  0
mfcc4_mean                 0
mfcc4_var                  0
mfcc5_mean                 0
mfcc5_var                  0
mfcc6_mean                 0
mfcc6_var                  0
mfcc7_mean                 0
mfcc7_var                  0
mfcc8_mean                 0
mfcc8_var     

In [166]:
df.isna().sum()

filename                   0
length                     0
chroma_stft_mean           0
chroma_stft_var            0
rms_mean                   0
rms_var                    0
spectral_centroid_mean     0
spectral_centroid_var      0
spectral_bandwidth_mean    0
spectral_bandwidth_var     0
rolloff_mean               0
rolloff_var                0
zero_crossing_rate_mean    0
zero_crossing_rate_var     0
harmony_mean               0
harmony_var                0
perceptr_mean              0
perceptr_var               0
tempo                      0
mfcc1_mean                 0
mfcc1_var                  0
mfcc2_mean                 0
mfcc2_var                  0
mfcc3_mean                 0
mfcc3_var                  0
mfcc4_mean                 0
mfcc4_var                  0
mfcc5_mean                 0
mfcc5_var                  0
mfcc6_mean                 0
mfcc6_var                  0
mfcc7_mean                 0
mfcc7_var                  0
mfcc8_mean                 0
mfcc8_var     

In [167]:
df[df == 0].count()

filename                   0
length                     0
chroma_stft_mean           0
chroma_stft_var            0
rms_mean                   0
rms_var                    0
spectral_centroid_mean     0
spectral_centroid_var      0
spectral_bandwidth_mean    0
spectral_bandwidth_var     0
rolloff_mean               0
rolloff_var                0
zero_crossing_rate_mean    0
zero_crossing_rate_var     0
harmony_mean               0
harmony_var                0
perceptr_mean              0
perceptr_var               0
tempo                      0
mfcc1_mean                 0
mfcc1_var                  0
mfcc2_mean                 0
mfcc2_var                  0
mfcc3_mean                 0
mfcc3_var                  0
mfcc4_mean                 0
mfcc4_var                  0
mfcc5_mean                 0
mfcc5_var                  0
mfcc6_mean                 0
mfcc6_var                  0
mfcc7_mean                 0
mfcc7_var                  0
mfcc8_mean                 0
mfcc8_var     

# Matriz de covarianzas y Outliers 

In [168]:
x = df.loc[:, 'chroma_stft_mean':'mfcc20_var']
y  = df['label'].cat.codes.values

In [169]:
def mahalanobis(x=None, data=None, cov=None):

    x_mu = x - np.mean(data)
    #if not cov:
        #cov = np.cov(x.T)
    inv_cov = np.linalg.inv(cov)
    mahalanobis_distances = np.diag(np.dot((x_mu @ inv_cov), x_mu.T))
   
    return mahalanobis_distances

In [170]:
data = df.iloc[:,2:-1]

In [171]:
x_train, x_test, y_train, y_test = train_test_split(x, y)

In [255]:
model = RandomForestClassifier()
model.fit(x_train, y_train)
train_og = model.score(x_train, y_train)
test_og = model.score(x_test, y_test)

print(train_og)
print(test_og)

0.9993326214628937
0.8618895116092874


## Con los datos originales

###### Con la covarianza habitual

In [173]:
cov_h = np.cov(x.T)
cond_h = np.linalg.cond(cov_h)
det_h = np.linalg.det(cov_h)

print("\nNúmero Condición: ",cond_h)
print("\nDeterminante: ",det_h)


Número Condición:  3.524299544710206e+18

Determinante:  3.6569422689130836e+105


In [174]:
mahalanobis_dis_h = mahalanobis(x=x, data=data, cov=cov_h)
mahalanobis_dis_h

array([ 18.4926218 ,  15.08558141,  20.29914978, ..., 101.8613797 ,
        23.37764574,  48.06979057])

##### Covarianza lamda veces la identidad

In [175]:
cov_h.shape

(57, 57)

In [176]:
cov_i = cov_h + 10*np.eye(57, 57) ## ¿Cómo determinamos lamda?
cond_i = np.linalg.cond(cov_i)
det_i = np.linalg.det(cov_i)

print("\nNúmero Condición: ",cond_i)
print("\nDeterminante: ",det_i)


Número Condición:  234533588498.06708

Determinante:  1.775108239035413e+165


In [177]:
mahalanobis_dis_i = mahalanobis(x=x, data=data, cov=cov_i)
mahalanobis_dis_i

array([11.99484394, 10.53799185, 14.53019315, ..., 86.19090744,
       16.93473188, 38.98463028])

##### Covarianza con shranke Ledoit and Wolf

In [178]:
from sklearn.covariance import LedoitWolf

In [179]:
cov_CLW = LedoitWolf().fit(x)
cov_CLW  = cov_CLW.covariance_

cond_clw= np.linalg.cond(cov_CLW)
det_clw = np.linalg.det(cov_CLW)

print("\nNúmero Condición: ",cond_clw)
print("\nDeterminante: ",det_clw)


Número Condición:  91440.01919261829

Determinante:  inf


C:\Users\Sara Gallego\anaconda3\lib\site-packages\numpy\linalg\linalg.py:2158: RuntimeWarning:

overflow encountered in det



In [180]:
mahalanobis_dis_clw = mahalanobis(x=x, data=data, cov=cov_CLW)
mahalanobis_dis_clw

array([0.70014859, 0.57328373, 0.59921995, ..., 8.58862809, 0.98317274,
       0.14691448])

##### Covarianza con minima curtosis

In [181]:
import scipy.stats as stats

In [182]:
kurtosis = stats.kurtosis(data)

##### Covarianza shrunk

In [183]:
from sklearn.covariance import ShrunkCovariance

In [184]:
cov_shr = ShrunkCovariance().fit(x)
cov_shr  = cov_shr.covariance_

cond_shr= np.linalg.cond(cov_shr)
det_shr = np.linalg.det(cov_shr)

print("\nNúmero Condición: ",cond_shr)
print("\nDeterminante: ",det_shr)


Número Condición:  498.6269673523012

Determinante:  inf


C:\Users\Sara Gallego\anaconda3\lib\site-packages\numpy\linalg\linalg.py:2158: RuntimeWarning:

overflow encountered in det



In [185]:
mahalanobis_dis_shr = mahalanobis(x=x, data=data, cov=cov_shr)
mahalanobis_dis_shr

array([0.48674438, 0.62350513, 0.53798187, ..., 0.76700033, 0.77201029,
       0.0263916 ])

##### Covarianza OAS

In [186]:
from sklearn.covariance import OAS

In [187]:
cov_oas = OAS().fit(x)
cov_oas  = cov_oas.covariance_

cond_oas= np.linalg.cond(cov_oas)
det_oas = np.linalg.det(cov_oas)

print("\nNúmero Condición: ",cond_oas)
print("\nDeterminante: ",det_oas)


Número Condición:  262888.9681854386

Determinante:  inf


C:\Users\Sara Gallego\anaconda3\lib\site-packages\numpy\linalg\linalg.py:2158: RuntimeWarning:

overflow encountered in det



In [188]:
mahalanobis_dis_oas = mahalanobis(x=x, data=data, cov=cov_oas)
mahalanobis_dis_oas

array([ 0.70933804,  0.57680689,  0.72554745, ..., 17.35712409,
        1.06940367,  0.28817925])

###### Covarianza Empirical

In [189]:
from sklearn.covariance import EmpiricalCovariance

In [190]:
cov_epm = EmpiricalCovariance().fit(x)
cov_epm  = cov_epm.covariance_

cond_epm= np.linalg.cond(cov_epm)
det_epm = np.linalg.det(cov_epm)

print("\nNúmero Condición: ",cond_epm)
print("\nDeterminante: ",det_epm)


Número Condición:  3.523003242663915e+18

Determinante:  3.636135207068209e+105


In [191]:
mahalanobis_dis_epm = mahalanobis(x=x, data=data, cov=cov_epm)
mahalanobis_dis_epm

array([ 18.4944731 ,  15.08709163,  20.30118193, ..., 101.87157705,
        23.37998608,  48.07460284])

#### Comparación 

In [192]:
num_cond = {'Num Condición Covarianza habitual': cond_h,
        'Num Condición Covarianza +lamba-identidad': cond_i,
        'Num Condición Covarianza con Shrinke Ledoit and Wolf': cond_clw,
        'Num Condición Covarianza Shrunk': cond_shr,
        'Num Condición Covarianza OAS': cond_oas,
        'Num Condición Covarianza Empirial': cond_epm
        }
num_cond

{'Num Condición Covarianza habitual': 3.524299544710206e+18,
 'Num Condición Covarianza +lamba-identidad': 234533588498.06708,
 'Num Condición Covarianza con Shrinke Ledoit and Wolf': 91440.01919261829,
 'Num Condición Covarianza Shrunk': 498.6269673523012,
 'Num Condición Covarianza OAS': 262888.9681854386,
 'Num Condición Covarianza Empirial': 3.523003242663915e+18}

In [193]:
determinante = {'Determinante Covarianza habitual': det_h,
        'Determinante Covarianza +lamba-identidad': det_i,
        'Determinante Covarianza con Shrinke Ledoit and Wolf': det_clw,
        'Determinante Covarianza Shrunk': det_shr,
        'Determinante Covarianza OAS': det_oas,
        'Determinante Covarianza Empirial': det_epm
        }
determinante

{'Determinante Covarianza habitual': 3.6569422689130836e+105,
 'Determinante Covarianza +lamba-identidad': 1.775108239035413e+165,
 'Determinante Covarianza con Shrinke Ledoit and Wolf': inf,
 'Determinante Covarianza Shrunk': inf,
 'Determinante Covarianza OAS': inf,
 'Determinante Covarianza Empirial': 3.636135207068209e+105}

###### Usando la distancia de mahalanobis de la matriz de covarianza de shrunk

In [194]:
fig = px.box(y=mahalanobis_dis_shr)
fig.show()

In [201]:
x_filtered = x[mahalanobis_dis_shr < 5]
y_filtered = y[mahalanobis_dis_shr < 5]

In [202]:
x_train_filtered, x_test_filtered, y_train_filtered, y_test_filtered = train_test_split(x_filtered, y_filtered)

In [256]:
model = RandomForestClassifier()
model.fit(x_train_filtered, y_train_filtered)
train_og_cov_shr = model.score(x_train_filtered, y_train_filtered)
test_og_cov_shr = model.score(x_test_filtered, y_test_filtered)

print(train_og_cov_shr)
print(test_og_cov_shr)

0.9993972272453285
0.8453887884267631


## Con los datos normalizados

In [204]:
scaler = MinMaxScaler()
x_norm = scaler.fit_transform(x)
x_norm

array([[0.3553988 , 0.71675699, 0.29313326, ..., 0.02679679, 0.50674637,
        0.04778078],
       [0.36732176, 0.67034733, 0.25303986, ..., 0.08241395, 0.59302914,
        0.06554772],
       [0.37315856, 0.72806736, 0.29675262, ..., 0.0438406 , 0.5462638 ,
        0.03606165],
       ...,
       [0.37419556, 0.69754793, 0.11650327, ..., 0.03992147, 0.50593726,
        0.04538043],
       [0.43653695, 0.65774457, 0.1482664 , ..., 0.01910101, 0.51990048,
        0.01373955],
       [0.40815099, 0.67614332, 0.11224896, ..., 0.03194326, 0.46137225,
        0.03454808]])

In [205]:
data_norm = scaler.fit_transform(data)

In [206]:
x_train_n, x_test_n, y_train_n, y_test_n = train_test_split(x_norm, y)

In [257]:
model = RandomForestClassifier()
model.fit(x_train_n, y_train_n)
train_norm = model.score(x_train_n, y_train_n)
test_norm = model.score(x_test_n, y_test_n)

print(train_norm)
print(test_norm)

0.9987987186332088
0.8498799039231385


##### Covarianza habitual

In [137]:
cov_h_norm = np.cov(x_norm.T)
cond_h_norm = np.linalg.cond(cov_h_norm)
det_h_norm = np.linalg.det(cov_h_norm)

print("\nNúmero Condición: ",cond_h_norm)
print("\nDeterminante: ",det_h_norm)


Número Condición:  1941.9940335474155

Determinante:  1.4519400069717303e-142


In [142]:
mahalanobis_dis_h_norm = mahalanobis(x=x_norm, data=data_norm, cov=cov_h_norm)
mahalanobis_dis_h_norm

array([563.82322382, 539.01329954, 577.82759164, ..., 560.8910044 ,
       557.45550061, 558.8965494 ])

##### Covarianza +lamba veces la identidad

In [143]:
cov_i_norm = cov_h_norm + 10*np.eye(57, 57) ## ¿Cómo determinamos lamda?
cond_i_norm = np.linalg.cond(cov_i_norm)
det_i_norm = np.linalg.det(cov_i_norm)

print("\nNúmero Condición: ",cond_i_norm)
print("\nDeterminante: ",det_i_norm)


Número Condición:  1.0163071405793629

Determinante:  1.0626616873361564e+57


In [144]:
mahalanobis_dis_i_norm = mahalanobis(x=x_norm, data=data_norm, cov=cov_i_norm)
mahalanobis_dis_i_norm

array([0.2474522 , 0.26380982, 0.27593943, ..., 0.23822693, 0.31191332,
       0.28965567])

##### Covarianza con shranke de Ledoit and Wolf

In [145]:
cov_CLW_norm = LedoitWolf().fit(x_norm)
cov_CLW_norm  = cov_CLW_norm.covariance_

cond_clw_norm= np.linalg.cond(cov_CLW_norm)
det_clw_norm = np.linalg.det(cov_CLW_norm)

print("\nNúmero Condición: ",cond_clw_norm)
print("\nDeterminante: ",det_clw_norm)


Número Condición:  1685.5056923112625

Determinante:  2.469082580355517e-142


In [147]:
mahalanobis_dis_clw_norm = mahalanobis(x=x_norm, data=data_norm, cov=cov_CLW_norm)
mahalanobis_dis_clw_norm

array([555.80275009, 531.87651832, 570.49121448, ..., 552.68302704,
       550.32660951, 552.40736755])

##### Covarianza con minima curtosis

##### Covarianza con shrunk

In [148]:
cov_shr_norm = ShrunkCovariance().fit(x_norm)
cov_shr_norm  = cov_shr_norm.covariance_

cond_shr_norm= np.linalg.cond(cov_shr_norm)
det_shr_norm = np.linalg.det(cov_shr_norm)

print("\nNúmero Condición: ",cond_shr_norm)
print("\nDeterminante: ",det_shr_norm)


Número Condición:  129.08497324478105

Determinante:  4.5245758148083806e-133


In [149]:
mahalanobis_dis_shr_norm = mahalanobis(x=x_norm, data=data_norm, cov=cov_shr_norm)
mahalanobis_dis_shr_norm

array([361.71763131, 353.84785686, 382.71409678, ..., 349.3077165 ,
       369.60252055, 374.26871657])

##### Covarianza OAS

In [150]:
cov_oas_norm = OAS().fit(x_norm)
cov_oas_norm  = cov_oas_norm.covariance_

cond_oas_norm= np.linalg.cond(cov_oas_norm)
det_oas_norm = np.linalg.det(cov_oas_norm)

print("\nNúmero Condición: ",cond_oas_norm)
print("\nDeterminante: ",det_oas_norm)


Número Condición:  1709.2555565006483

Determinante:  2.3371177019898893e-142


In [151]:
mahalanobis_dis_oas_norm = mahalanobis(x=x_norm, data=data_norm, cov=cov_oas_norm)
mahalanobis_dis_oas_norm

array([556.6122714 , 532.59784973, 571.2348806 , ..., 553.51491082,
       551.04944557, 553.06955808])

##### Covarianza empirical

In [225]:
cov_epm_norm = EmpiricalCovariance().fit(x_norm)
cov_epm_norm  = cov_epm_norm.covariance_

cond_epm_norm = np.linalg.cond(cov_epm_norm)
det_epm_norm = np.linalg.det(cov_epm_norm)

print("\nNúmero Condición: ",cond_epm_norm)
print("\nDeterminante: ",det_epm_norm)


Número Condición:  1941.994033547307

Determinante:  1.4436788414135746e-142


In [226]:
mahalanobis_dis_epm_norm = mahalanobis(x=x_norm, data=data_norm, cov=cov_epm_norm)
mahalanobis_dis_epm_norm

array([563.87966823, 539.06726023, 577.88543803, ..., 560.94715527,
       557.51130754, 558.9525006 ])

#### Comparación

In [154]:
num_cond_norm = {'Num Condición Covarianza habitual': cond_h_norm,
        'Num Condición Covarianza +lamba-identidad': cond_i_norm,
        'Num Condición Covarianza con Shrinke Ledoit and Wolf': cond_clw_norm,
        'Num Condición Covarianza Shrunk': cond_shr_norm,
        'Num Condición Covarianza OAS': cond_oas_norm,
        'Num Condición Covarianza Empirial': cond_epm_norm
        }
num_cond_norm

{'Num Condición Covarianza habitual': 1941.9940335474155,
 'Num Condición Covarianza +lamba-identidad': 1.0163071405793629,
 'Num Condición Covarianza con Shrinke Ledoit and Wolf': 1685.5056923112625,
 'Num Condición Covarianza Shrunk': 129.08497324478105,
 'Num Condición Covarianza OAS': 1709.2555565006483,
 'Num Condición Covarianza Empirial': 3.523003242663915e+18}

In [155]:
determinante_norm = {'Determinante Covarianza habitual': det_h_norm,
        'Determinante Covarianza +lamba-identidad': det_i_norm,
        'Determinante Covarianza con Shrinke Ledoit and Wolf': det_clw_norm,
        'Determinante Covarianza Shrunk': det_shr_norm,
        'Determinante Covarianza OAS': det_oas_norm,
        'Determinante Covarianza Empirial': det_epm_norm
        }
determinante_norm

{'Determinante Covarianza habitual': 1.4519400069717303e-142,
 'Determinante Covarianza +lamba-identidad': 1.0626616873361564e+57,
 'Determinante Covarianza con Shrinke Ledoit and Wolf': 2.469082580355517e-142,
 'Determinante Covarianza Shrunk': 4.5245758148083806e-133,
 'Determinante Covarianza OAS': 2.3371177019898893e-142,
 'Determinante Covarianza Empirial': 3.636135207068209e+105}

###### Usando la distancia de mahalanobis de la matriz de covarianza +lamba veces la identidad

In [156]:
fig = px.box(y=mahalanobis_dis_i_norm)
fig.show()

In [208]:
x_filtered_norm = x_norm[mahalanobis_dis_i_norm < 0.4]
y_filtered_norm = y[mahalanobis_dis_i_norm < 0.4]

In [209]:
x_train_filtered_n, x_test_filtered_n, y_train_filtered_n, y_test_filtered_n = train_test_split(x_filtered_norm, 
                                                                                                y_filtered_norm)

In [259]:
model = RandomForestClassifier()
model.fit(x_train_filtered_n, y_train_filtered_n)
train_norm_cov_i = model.score(x_train_filtered_n, y_train_filtered_n)
test_norm_cov_i = model.score(x_test_filtered_n, y_test_filtered_n)

print(train_norm_cov_i)
print(test_norm_cov_i)

0.9993268712977922
0.8788368336025848


## Con los datos estandarizados

In [211]:
scaler = StandardScaler()
x_sc = scaler.fit_transform(x)
x_sc

array([[-0.48780784,  0.64052047, -0.00662408, ..., -0.51356204,
         0.12841417, -0.29178072],
       [-0.40314187,  0.13183473, -0.26494432, ...,  1.01138445,
         1.27578001,  0.05642464],
       [-0.36169428,  0.7644909 ,  0.01669533, ..., -0.04624405,
         0.65390663, -0.52145798],
       ...,
       [-0.35433044,  0.42997426, -1.14464442, ..., -0.15370124,
         0.11765485, -0.33882395],
       [ 0.0883611 , -0.00630133, -0.93999575, ..., -0.72456977,
         0.30333409, -0.95893743],
       [-0.11321002,  0.19536324, -1.17205474, ..., -0.37245283,
        -0.47495901, -0.55112155]])

In [212]:
data_sc = scaler.fit_transform(data)

In [213]:
x_train_sc, x_test_sc, y_train_sc, y_test_sc = train_test_split(x_sc, y)

In [260]:
model = RandomForestClassifier()
model.fit(x_train_sc, y_train_sc)
train_sc = model.score(x_train_sc, y_train_sc)
test_sc = model.score(x_test_sc, y_test_sc)

print(train_sc)
print(test_sc)

0.9991991457554725
0.8566853482786229


##### Covarianza habitual

In [215]:
cov_h_sc = np.cov(x_sc.T)
cond_h_sc = np.linalg.cond(cov_h_sc)
det_h_sc = np.linalg.det(cov_h_sc)

print("\nNúmero Condición: ",cond_h_sc)
print("\nDeterminante: ",det_h_sc)


Número Condición:  3287.784059810006

Determinante:  6.573103522557816e-24


In [216]:
mahalanobis_dis_h_sc = mahalanobis(x=x_sc, data=data_sc, cov=cov_h_sc)
mahalanobis_dis_h_sc

array([ 18.4926218 ,  15.08558141,  20.29914978, ..., 101.8613797 ,
        23.37764574,  48.06979057])

#### Covarianza +lamba veces la identidad

In [217]:
cov_i_sc = cov_h_sc + 10*np.eye(57, 57) ## ¿Cómo determinamos lamda?
cond_i_sc = np.linalg.cond(cov_i_sc)
det_i_sc = np.linalg.det(cov_i_sc)

print("\nNúmero Condición: ",cond_i_sc)
print("\nDeterminante: ",det_i_sc)


Número Condición:  2.1425036123338512

Determinante:  1.2212343261970865e+59


In [218]:
mahalanobis_dis_i_sc = mahalanobis(x=x_sc, data=data_sc, cov=cov_i_sc)
mahalanobis_dis_i_sc

array([0.93187867, 1.05601396, 1.11008668, ..., 6.1694345 , 2.04369096,
       2.99999676])

##### Covarianza con shranke de Ledoit and Wolf

In [219]:
cov_CLW_sc = LedoitWolf().fit(x_sc)
cov_CLW_sc  = cov_CLW_sc.covariance_

cond_clw_sc= np.linalg.cond(cov_CLW_sc)
det_clw_sc = np.linalg.det(cov_CLW_sc)

print("\nNúmero Condición: ",cond_clw_sc)
print("\nDeterminante: ",det_clw_sc)


Número Condición:  1853.5895907538286

Determinante:  2.719914823227153e-23


In [220]:
mahalanobis_dis_clw_sc = mahalanobis(x=x_sc, data=data_sc, cov=cov_CLW_sc)
mahalanobis_dis_clw_sc

array([ 18.16584231,  14.80616504,  20.1468577 , ..., 100.56819827,
        22.8938964 ,  47.39207556])

##### Covarianza con minima curtosis

##### Covarianza con shrunk

In [221]:
cov_shr_sc = ShrunkCovariance().fit(x_sc)
cov_shr_sc  = cov_shr_sc.covariance_

cond_shr_sc= np.linalg.cond(cov_shr_sc)
det_shr_sc = np.linalg.det(cov_shr_sc)

print("\nNúmero Condición: ",cond_shr_sc)
print("\nDeterminante: ",det_shr_sc)


Número Condición:  100.73000993162852

Determinante:  4.911051826384011e-16


In [222]:
mahalanobis_dis_shr_sc = mahalanobis(x=x_sc, data=data_sc, cov=cov_shr_sc)
mahalanobis_dis_shr_sc

array([14.79129588, 11.95764788, 17.00088394, ..., 85.28007047,
       19.18870877, 41.21605606])

##### Covarianza con OAS

In [223]:
cov_oas_sc = OAS().fit(x_sc)
cov_oas_sc  = cov_oas_sc.covariance_

cond_oas_sc= np.linalg.cond(cov_oas_sc)
det_oas_sc = np.linalg.det(cov_oas_sc)

print("\nNúmero Condición: ",cond_oas_sc)
print("\nDeterminante: ",det_oas_sc)


Número Condición:  2221.154675298444

Determinante:  1.6691865370343928e-23


In [224]:
mahalanobis_dis_oas_sc = mahalanobis(x=x_sc, data=data_sc, cov=cov_oas_sc)
mahalanobis_dis_oas_sc

array([ 18.27007552,  14.8999466 ,  20.20258491, ..., 101.02071744,
        23.05887706,  47.60676497])

##### Covarianza empirical

In [227]:
cov_epm_sc = EmpiricalCovariance().fit(x_sc)
cov_epm_sc  = cov_epm_sc.covariance_

cond_epm_sc = np.linalg.cond(cov_epm_sc)
det_epm_sc = np.linalg.det(cov_epm_sc)

print("\nNúmero Condición: ",cond_epm_sc)
print("\nDeterminante: ",det_epm_sc)


Número Condición:  3287.7840598098337

Determinante:  6.535704252499416e-24


In [228]:
mahalanobis_dis_epm_sc = mahalanobis(x=x_sc, data=data_sc, cov=cov_epm_sc)
mahalanobis_dis_epm_sc

array([ 18.4944731 ,  15.08709163,  20.30118193, ..., 101.87157705,
        23.37998608,  48.07460284])

##### Comparacion

In [230]:
num_cond_sc = {'Num Condición Covarianza habitual': cond_h_sc,
        'Num Condición Covarianza +lamba-identidad': cond_i_sc,
        'Num Condición Covarianza con Shrinke Ledoit and Wolf': cond_clw_sc,
        'Num Condición Covarianza Shrunk': cond_shr_sc,
        'Num Condición Covarianza OAS': cond_oas_sc,
        'Num Condición Covarianza Empirial': cond_epm_sc
        }
num_cond_sc

{'Num Condición Covarianza habitual': 3287.784059810006,
 'Num Condición Covarianza +lamba-identidad': 2.1425036123338512,
 'Num Condición Covarianza con Shrinke Ledoit and Wolf': 1853.5895907538286,
 'Num Condición Covarianza Shrunk': 100.73000993162852,
 'Num Condición Covarianza OAS': 2221.154675298444,
 'Num Condición Covarianza Empirial': 3287.7840598098337}

In [231]:
determinante_sc = {'Determinante Covarianza habitual': det_h_sc,
        'Determinante Covarianza +lamba-identidad': det_i_sc,
        'Determinante Covarianza con Shrinke Ledoit and Wolf': det_clw_sc,
        'Determinante Covarianza Shrunk': det_shr_sc,
        'Determinante Covarianza OAS': det_oas_sc,
        'Determinante Covarianza Empirial': det_epm_sc
        }
determinante_sc

{'Determinante Covarianza habitual': 6.573103522557816e-24,
 'Determinante Covarianza +lamba-identidad': 1.2212343261970865e+59,
 'Determinante Covarianza con Shrinke Ledoit and Wolf': 2.719914823227153e-23,
 'Determinante Covarianza Shrunk': 4.911051826384011e-16,
 'Determinante Covarianza OAS': 1.6691865370343928e-23,
 'Determinante Covarianza Empirial': 6.535704252499416e-24}

###### Usando la distancia de mahalanobis de la matriz de covarianza +lamba veces la identidad

In [233]:
fig = px.box(y=mahalanobis_dis_i_sc)
fig.show()

In [234]:
x_filtered_sc = x_norm[mahalanobis_dis_i_sc < 8]
y_filtered_sc = y[mahalanobis_dis_i_sc < 8]

In [235]:
x_train_filtered_sc, x_test_filtered_sc, y_train_filtered_sc, y_test_filtered_sc = train_test_split(x_filtered_sc, 
                                                                                                y_filtered_sc)

In [261]:
model = RandomForestClassifier()
model.fit(x_train_filtered_sc, y_train_filtered_sc)
train_sc_cov_i = model.score(x_train_filtered_sc, y_train_filtered_sc)
test_sc_cov_i = model.score(x_test_filtered_sc, y_test_filtered_sc)

print(train_sc_cov_i)
print(test_sc_cov_i)

0.9989890236857308
0.8626516464471404


## Comparación general

In [270]:
scores_train = [train_og, train_og_cov_shr, train_norm, train_norm_cov_i, train_sc, train_sc_cov_i]
scores_train

[0.9993326214628937,
 0.9993972272453285,
 0.9987987186332088,
 0.9993268712977922,
 0.9991991457554725,
 0.9989890236857308]

In [272]:
scores_test = [test_og, test_og_cov_shr, test_norm, test_norm_cov_i, test_sc, test_sc_cov_i]
scores_test

[0.8618895116092874,
 0.8453887884267631,
 0.8498799039231385,
 0.8788368336025848,
 0.8566853482786229,
 0.8626516464471404]

In [277]:
index = ['scores train', 'scores test']
columns = ['Datos originales', 'Datos originales Cov Shrunk', 'Datos normalizados', 'Datos normalizados Cov +lamba-ide',
          'Datos escalados', 'Datos escalados Cov +lamba-ide']

In [278]:
df_scores = pd.DataFrame([scores_train,scores_test], columns = columns, index=index) 
  
df_scores

Datos originales  Datos originales Cov Shrunk  \
scores train          0.999333                     0.999397   
scores test           0.861890                     0.845389   

              Datos normalizados  Datos normalizados Cov +lamba-ide  \
scores train            0.998799                           0.999327   
scores test             0.849880                           0.878837   

              Datos escalados  Datos escalados Cov +lamba-ide  
scores train         0.999199                        0.998989  
scores test          0.856685                        0.862652